In [ ]:
import pandas as pd
import json
import os
import numpy as np

from datasets import Dataset
from ragas import evaluate
from ragas.metrics import faithfulness, answer_relevancy
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

In [ ]:
def load_jsonl(path):
    data = []
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            data.append(json.loads(line))
    return pd.DataFrame(data)

def calc_retrieval_metrics(row, agent='baseline', k=3):
    # FIXED: Support both old and new result structures
    if agent in row and isinstance(row[agent], dict) and 'ids' in row[agent]:
        retrieved_ids = row[agent]['ids'][:k]
    elif f'{agent}_retrieved_ids' in row:
        retrieved_ids = row[f'{agent}_retrieved_ids'][:k]
    else:
        return pd.Series([0.0, 0.0, 0.0])

    gt_ids = [m['chunk_id'] for m in row['chunk_metadata']]
    gt_set = set(gt_ids)

    hits = [1 if doc_id in gt_set else 0 for doc_id in retrieved_ids]

    recall = sum(hits) / len(gt_set) if len(gt_set) > 0 else 0.0
    precision = sum(hits) / k if k > 0 else 0.0

    mrr = 0.0
    for i, hit in enumerate(hits):
        if hit == 1:
            mrr = 1.0 / (i + 1)
            break

    return pd.Series([precision, recall, mrr])
from config import Config

In [ ]:
os.environ["OPENAI_API_KEY"] = os.getenv('OPENAI_API_KEY')
from config import Config

d:\Kuliah\SKRIPSI\code\playground\skripsi-playground-venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\jayaw\AppData\Local\Temp\ipykernel_42176\971595098.py:7: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import faithfulness, answer_relevancy
C:\Users\jayaw\AppData\Local\Temp\ipykernel_42176\971595098.py:7: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import faithfulness, answer_relevancy

In [2]:
langchain_llm = ChatOpenAI(model="gpt-4o-mini")
langchain_embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

evaluator_llm = LangchainLLMWrapper(langchain_llm)
evaluator_embeddings = LangchainEmbeddingsWrapper(langchain_embeddings)

C:\Users\jayaw\AppData\Local\Temp\ipykernel_42176\770287758.py:4: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(langchain_llm)
C:\Users\jayaw\AppData\Local\Temp\ipykernel_42176\770287758.py:5: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = LangchainEmbeddingsWrapper(langchain_embeddings)

In [ ]:
K_VALUE = Config.TOP_K
FILEPATH = f"knowledge-base/20260429_1829_rag_responses_dataset_k3.jsonl"

In [4]:
print("1. Memuat data hasil evaluasi...")
data_list = []
with open(FILEPATH, "r", encoding="utf-8") as f:
    for line in f:
        data_list.append(json.loads(line.strip()))

df = pd.DataFrame(data_list)
print(f"Total data dimuat: {len(df)} baris.\n")

# Ekstrak Kunci Jawaban ID (Ground Truth IDs) dari metadata
df['ground_truth_ids'] = df['chunk_metadata'].apply(lambda x: [meta['chunk_id'] for meta in x] if isinstance(x, list) else [])

# 1A. EKSTRAK ID RETRIEVAL DARI METADATA (MODIFIKASI BARU)
df['baseline_retrieved_ids'] = df['baseline_contexts_metadata'].apply(
    lambda x: [meta['chunk_id'] for meta in x] if isinstance(x, list) else []
)
df['fusion_retrieved_ids'] = df['fusion_contexts_metadata'].apply(
    lambda x: [meta['chunk_id'] for meta in x] if isinstance(x, list) else []
)

# 1B. BERSIHKAN TEKS JAWABAN DARI PROMPT (MODIFIKASI BARU)
def extract_final_answer(full_text):
    """Memotong prompt LLM dan hanya mengambil jawaban akhirnya saja"""
    if not isinstance(full_text, str):
        return ""
    
    # Token penanda di mana asisten mulai menjawab
    split_token = "<|im_start|>assistant\n"
    
    if split_token in full_text:
        # Ambil semua teks setelah token asisten
        return full_text.split(split_token)[-1].strip()
    return full_text.strip()

# Buat kolom baru berisi jawaban yang sudah bersih
df['clean_baseline_answer'] = df['baseline_answer'].apply(extract_final_answer)
df['clean_fusion_answer'] = df['fusion_answer'].apply(extract_final_answer)

1. Memuat data hasil evaluasi...
Total data dimuat: 50 baris.

In [5]:
df

,question,ground_truth,chunk_metadata,baseline_answer,baseline_contexts_metadata,baseline_retrieved_contexts,fusion_answer,fusion_contexts_metadata,fusion_retrieved_contexts,ground_truth_ids,baseline_retrieved_ids,fusion_retrieved_ids,clean_baseline_answer,clean_fusion_answer
0,Bagaimana pelaksanaan edukasi selama 15-30 men...,Pelaksanaan edukasi selama 15-30 menit bertuju...,[{'Header 2': 'RekapPengelolaan Penanganan Giz...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': '1. Tujuan', 'source': 'THORAX ...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '3.5 Edukasi Gizi', 'source': '...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[3449, 3427, 3424]","[3424, 3427, 3425]","[3442, 2548, 6882]",Edukasi selama 15–30 menit kepada orang tua pa...,Edukasi gizi yang dilaksanakan selama 15–30 me...
1,Apa hubungan antara pemberian makanan sehat da...,Pemberian makanan sehat berperan penting dalam...,[{'Header 2': 'RekapPengelolaan Penanganan Giz...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': '1. Tujuan', 'source': 'THORAX ...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'a. Riwayat Gizi Dahulu', 'sourc...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[3449, 3427, 3424]","[3424, 3425, 3429]","[6443, 5435, 3444]",Tidak ada hubungan secara langsung antara pemb...,Pemberian makanan sehat memiliki hubungan pent...
2,Bagaimana hubungan antara kondisi prehipertens...,Pasien mengalami prehipertensi yang memerlukan...,[{'Header 2': '3.3 Monitoring dan Evaluasi Fis...,Human: <|im_start|>system\nAnda adalah asisten...,[{'Header 2': 'PENATALAKSANAAN GIZI PADA PASIE...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '2.2.4 Fisik Klinis', 'source':...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[4625, 4652, 4618]","[4599, 4653, 4597]","[4610, 4621, 4624]",Tidak ada informasi dalam konteks tentang reko...,Kondisi prehipertensi pasien menunjukkan bahwa...
3,Apa yang dapat disimpulkan tentang status gizi...,"Pasien tidak berisiko mengalami malnutrisi, ya...",[{'Header 2': '3.3 Monitoring dan Evaluasi Fis...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Kesimpulan :', 'source': 'PASIE...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'BAB IV PEMBAHASAN', 'source': '...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[4625, 4652, 4618]","[4653, 4646, 4645]","[1114, 4646, 1553]",Pasien memiliki indeks massa tubuh (IMT) sebes...,"Pasien dengan berat badan 52 kg, tinggi badan ..."
4,Apa hubungan antara penurunan kesadaran pasien...,Penurunan kesadaran pasien yang ditunjukkan de...,[{'Header 2': 'Lampiran 8. Dokumentasi Skrinin...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'B. Sasaran', 'source': 'Penuru...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,[{'Header 2': 'B. Monitoring dan Evaluasi Peme...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[4750, 4724, 4730]","[4708, 4748, 4659]","[4388, 2244, 4314]",Informasi tidak ditemukan. \n\nKonteks tidak ...,Informasi tentang pasien dengan jenis kelamin ...
5,Bagaimana kondisi bengkak pada mata pasien dap...,Kondisi bengkak pada mata pasien dapat dipenga...,[{'Header 2': 'Lampiran 8. Dokumentasi Skrinin...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'B. Prinsip Diet', 'source': 'P...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,ERROR,[{'Header 2': 'B. Monitoring dan Evaluasi Peme...,[],"[4750, 4724, 4730]","[4702, 4708, 4709]","[4388, 2244, 4314]",Bengkak pada mata pasien dapat dipengaruhi ole...,ERROR
6,Apa tujuan pemberian diet yang diberikan kepad...,Tujuan pemberian diet adalah untuk meningkatka...,"[{'Header 2': 'A. Tujuan', 'source': 'WEDGE E...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Lampiran 3. Media Edukasi', 's...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Keterangan:', 'source': 'DIAGNO...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[2205, 2232, 2214]","[2237, 2201, 2174]","[5419, 5900, 2022]",Tujuan pemberian diet bagi pasien perempuan us...,Informasi tidak ditemukan. \n\nAlasannya: Kon...
7,Bagaimana hasil monitoring kondisi pasien sela...,Hasil monitoring menunjukkan perbaikan kondisi...,"[{'Header 2': 'A. Tujuan', 'source': 'WEDGE E...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Keterangan Tabel', 'source': 'W...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Keterangan Tabel', 'source': 'W...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[2205, 2232, 2214]","[2174, 2213, 2232]","[2174, 5322, 4528]",Hasil monitoring kondisi pasien selama tiga ha...,Hasil monitoring kondisi pasien selama tiga ha...
8,Apa saja materi yang diajarkan kepada pasien u...,Materi yang diajarkan kepada pasien mencakup p...,"[{'Header 2': '2. Antropometri', 'source': 'PA...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Target:', 'source': 'PASIEN DEN...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Tujuan:', 'source': 'PASIEN DEN...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[2581, 2606, 2645]","[2603, 2612, 2614]","[2606, 2644, 2627]",Materi yang diajarkan kepada pasien mencakup p...,Materi yang diajarkan kepada pasien mencakup:\...
9,Bagaimana metode yang digunakan untuk meningka...,Metode yang digunakan untuk meningkatkan penge...,"[{'Header 2': '2. Antropometri', 'source': 'PA...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Target:', 'source': 'PASIEN DEN...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Tujuan:', 'source': 'PASIEN DEN...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[2581, 2606, 2645]","[2603, 2605, 2608]","[2606, 6636, 714]",Metode yang digunakan untuk meningkatkan penge...,Metode yang digunakan untuk meningkatkan penge...
10,Bagaimana latar belakang pendidikan orangtua p...,Orangtua pasien memiliki pendidikan terakhir S...,"[{'Header 2': '2.3.2. Biokimia', 'source': 'D...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'b. Riwayat Personal', 'source'...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '2.5.2 Terapi Edukasi', 'source'...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[5423, 5433, 5470]","[5433, 5421, 5470]","[179, 5351, 2932]",Latar belakang pendidikan orangtua pasien (SMA...,Informasi tidak ditemukan. \n\nAlasan: Kontek...
11,Apa dampak dari rendahnya pengetahuan orangtua...,Rendahnya pengetahuan orangtua pasien tentang ...,"[{'Header 2': '2.3.2. Biokimia', 'source': 'D...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': '2.3.1. Antropometri', 'source'...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Dampak Kesehatan', 'source': 'G...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[5423, 5433, 5470]","[5421, 5433, 5454]","[4990, 714, 7023]",Rendahnya pengetahuan orangtua pasien tentang ...,"Informasi tentang pasien dengan usia 2 bulan, ..."
12,Apa yang perlu diperhatikan oleh orang tua ter...,Orang tua perlu lebih perhatian terhadap kecuk...,[{'Header 2': 'C. Pengaturan Makan Harian 1 Ja...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'B. Saran', 'source': 'ASTHMA SE...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'D. Hasil Pemantauan Cairan', '...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[1646, 1658, 1655]","[1658, 1668, 1637]","[1655, 1658, 2990]",Orang tua perlu memperhatikan pemantauan caira...,Orang tua perlu memperhatikan asupan dan kelua...
13,Bagaimana variasi makanan yang dikonsumsi pasi...,Variasi makanan yang dikonsumsi pasien dapat m...,[{'Header 2': 'C. Pengaturan Makan Harian 1 Ja...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'B. Saran', 'source': 'ASTHMA SE...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'B. Saran', 'source': 'ASTHMA SE...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[1646, 1658, 1655]","[1658, 1637, 1642]","[1658, 6881, 6144]",Variasi makanan yang dikonsumsi pasien dapat m...,Pasien laki-laki usia 6 tahun 6 bulan 21 hari ...
14,Bagaimana intervensi gizi yang dilakukan pada ...,Intervensi gizi yang dilakukan pada pasien den...,"[{'Header 2': '· Tujuan Umum', 'source': 'RPGN...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'A. TUJUAN', 'source': 'RPGN + ...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Keterangan:', 'source': 'RPGN +...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[1394, 1502, 1465]","[1436, 1437, 1407]","[1402, 1583, 949]",Intervensi gizi yang dilakukan pada pasien—yai...,"Pasien dengan usia 11 tahun 6 bulan, berat bad..."
15,Apa hubungan antara hasil assessment fisik pas...,Hasil assessment fisik pasien yang menunjukkan...,"[{'Header 2': '· Tujuan Umum', 'source': 'RPGN...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'NC 4.1 Malnutrisi', 'source': '...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '2.4. Analisis Masalah', 'source...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[1394, 1502, 1465]","[1502, 1435, 1407]","[2911, 4950, 2456]",Hubungan antara hasil assessment fisik pasien ...,Hubungan antara hasil assessment fisik pasien ...
16,Apa tujuan dari edukasi diet yang diberikan ke...,Tujuan dari edukasi diet adalah untuk memberik...,[{'Header 2': 'Hasil Monev Asupan Hari Pertama...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Media', 'source': 'DIAGNOSA MED...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '5.6 Pengetahuan Pasien', 'sourc...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[1606, 1571, 1553]","[1573, 1615, 1572]","[6041, 3105, 5890]",Tujuan edukasi diet yang diberikan kepada pasi...,Tujuan edukasi diet yang diberikan kepada pasi...
17,Apa saja materi yang disampaikan dalam edukasi...,Materi yang disampaikan dalam edukasi diet men...,[{'Header 2': 'Hasil Monev Asupan Hari Pertama...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Metode', 'source': 'DIAGNOSA ME...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '5.6 Pengetahuan Pasien', 'sourc...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[1606, 1571, 1553]","[1572, 1573, 1615]","[6041, 5058, 3730]",Materi edukasi diet yang disampaikan kepada pa...,Materi yang disampaikan dalam edukasi diet men...
18,Bagaimana penurunan nafsu makan yang dialami p...,Penurunan nafsu makan yang dialami pasien berk...,"[{'Header 2': '5.1 Kesimpulan', 'source': 'Pos...",Human: <|im_start|>system\nAnda adalah asisten...,[{'Header 2': 'Tujuan Diet Tinggi Energi Tingg...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '4.4 Pembahasan Fisik Klinis', '...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[1999, 2014, 1990]","[2016, 2012, 1961]","[1987, 5953, 5058]",Penurunan nafsu makan yang dialami pasien dapa...,Penurunan nafsu makan yang dialami pasien dapa...
19,Apa dampak dari asupan lemak yang melebihi tar...,Asupan lemak yang melebihi target selama inter...,"[{'Header 2': '5.1 Kesimpulan', 'source': 'Pos...",Human: <|im_start|>system\nAnda adalah asisten...,[{'Header 2': 'Tujuan Diet Tinggi Energi Tingg...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '· Lemak', 'source': 'FEBRIS + T...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[1999, 2014, 1990]","[2016, 1961, 2012]","[3349, 1578, 5875]",Informasi tidak ditemukan. \n\nKonteks tidak ...,Asupan lemak yang melebihi target (80% kebutuh...
20,Bagaimana penurunan nafsu makan pasien dapat m...,Penurunan nafsu makan pasien dapat menyebabkan...,"[{'Header 2': 'Riwayat Sekarang', 'source': 'P...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'a. Masalah Gizi', 'source': 'PA...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,[{'Header 2': '3.1.1. Monitoring dan Evaluasi...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[2508, 2507, 2542]","[2516, 2518, 2492]","[2534, 6393, 2931]",Penurunan nafsu makan pada pasien dapat secara...,Penurunan nafsu makan pasien dapat secara sign...
21,Apa hubungan antara diet yang diberikan kepada...,"Diet yang diberikan kepada pasien, yang terdir...","[{'Header 2': 'Riwayat Sekarang', 'source': 'P...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Riwayat Penyakit Keluarga', 'so...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Lampiran 2. SQ FFQ Assessment',...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[2508, 2507, 2542]","[2512, 2510, 2492]","[2553, 5678, 2492]",Informasi tidak ditemukan.,"Pasien dengan diagnosis diare kronis, HIV, PJB..."
22,Bagaimana pengaruh asupan lemak dan protein te...,Asupan lemak yang mencukupi dapat berperan seb...,"[{'Header 2': 'Prinsip :', 'source': 'Congenit...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Tujuan :', 'source': 'Congenita...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '5.2.2 Asupan Lemak', 'source': ...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[529, 514, 553]","[528, 540, 529]","[553, 1594, 540]",Asupan protein memiliki dampak penting terhada...,Pasien perempuan usia 1 tahun 2 bulan dengan d...
23,Apa hubungan antara kebutuhan energi dan asupa...,"Kebutuhan energi yang sesuai, yang dipengaruhi...","[{'Header 2': 'Prinsip :', 'source': 'Congenit...",Human: <|im_start|>system\nAnda adalah asisten...,[{'Header 2': 'Formulir Skrining Gizi Anak PYM...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,[{'Header 2': 'RiwayatTerkaitGizi Dan Makanan'...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[529, 514, 553]","[518, 528, 567]","[567, 571, 5319]",Pasien dengan diagnosis congenital absence atr...,Pasien dengan diagnosis *congenital absence at...
24,Bagaimana pengaruh diet ASIP + HMF terhadap as...,Diet ASIP + HMF memberikan asupan energi rata-...,"[{'Header 2': '5.2 Biokimia', 'source': 'BERAT...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Prinsip diet', 'source': 'BERAT...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Prinsip diet', 'source': 'BERAT...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[3517, 3498, 3504]","[3504, 3488, 3503]","[3504, 2807, 2987]",Diet ASIP + HMF (Asupan Suspensi Infan dan For...,Diet ASIP + HMF (Asupan Suspensi Infantil Plus...
25,Apa yang dapat disimpulkan mengenai status giz...,Pasien mendapatkan asupan cairan sebanyak 240 ...,"[{'Header 2': '5.2 Biokimia', 'source': 'BERAT...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'BAB I PENDAHULUAN', 'source': '...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'c) Asupan Lemak', 'source': 'B...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[3517, 3498, 3504]","[3488, 3503, 3523]","[483, 2988, 5478]","Berdasarkan data klinis pasien, dapat disimpul...",Status gizi pasien dapat disimpulkan sebagai *...
26,Apa tujuan dari terapi diet yang diberikan kep...,Tujuan dari terapi diet adalah untuk memenuhi ...,[{'Header 2': '2.2.2. Pengukuran Antropometri'...,Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Status Gizi BB/U (z-score)', 's...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '2.5 Intervensi Gizi', 'source'...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[3837, 3870, 3852]","[3838, 3836, 3866]","[3852, 3873, 3442]",Tujuan terapi diet pada pasien perempuan usia ...,Tujuan terapi diet yang diberikan kepada pasie...
27,Bagaimana intervensi diet tinggi energi dan pr...,Intervensi diet tinggi energi dan protein dapa...,[{'Header 2': '2.2.2. Pengukuran Antropometri'...,Human: <|im_start|>system\nAnda adalah asisten...,[{'Header 2': 'BAB 2 NUTRITIONAL CARE PROCESS'...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'Nutritional Care Process', 'sou...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[3837, 3870, 3852]","[3836, 3838, 3873]","[3873, 3852, 3939]",Intervensi diet tinggi energi dan protein bert...,Intervensi diet tinggi energi dan protein memb...
28,Bagaimana peningkatan asupan energi pasien dap...,Peningkatan asupan energi pasien yang mengalam...,"[{'Header 2': '4.4.1 Asupan Energi', 'source':...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Kesimpulan:', 'source': 'GIZI B...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'a. Asupan Energi', 'source': 'R...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[2278, 2248, 2286]","[2258, 2285, 2259]","[2446, 3217, 6158]",Peningkatan asupan energi pada pasien dengan g...,Informasi tidak ditemukan. \n\nAlasan: Kontek...
29,Apa hubungan antara diet yang disesuaikan deng...,Diet yang disesuaikan dengan kebutuhan pasien ...,"[{'Header 2': '4.4.1 Asupan Energi', 'source':...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'a. Skrining Gizi Strong Kid', '...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,ERROR,"[{'Header 2': 'a. Asupan Energi', 'source': 'R...",[],"[2278, 2248, 2286]","[2285, 2259, 2250]","[2446, 3217, 6158]",Pasien dengan diagnosis gizi buruk tipe marasm...,ERROR
30,Bagaimana perencanaan gizi yang tepat dapat me...,Perencanaan gizi yang tepat dapat membantu men...,"[{'Header 2': 'Syarat Diet', 'source': 'GIZI B...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': 'Tujuan Diet', 'source': 'GIZI B...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '2.9 Analisa Masalah', 'source':...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[5025, 5023, 5041]","[5023, 5024, 5068]","[5020, 5023, 342]",Perencanaan gizi yang tepat dapat membantu men...,Perencanaan gizi yang tepat dapat membantu men...
31,Apa saja komponen gizi yang harus diperhatikan...,Komponen gizi yang harus diperhatikan dalam pe...,"[{'Header 2': 'Syarat Diet', 'source': 'GIZI B...",Human: <|im_start|>system\nAnda adalah asisten...,[{'Header 2': 'Untuk pasien dan Keluarga Pasie...,[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': 'PAGI', 'source': 'DIAGNOSA MEDI...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[5025, 5023, 5041]","[5068, 5024, 5023]","[1619, 5072, 5333]",Komponen gizi yang harus diperhatikan dalam pe...,Komponen gizi yang harus diperhatikan dalam pe...
32,Bagaimana pengaruh peningkatan berat badan pas...,Peningkatan berat badan pasien sebesar 200 gra...,"[{'Header 2': 'Riwayat Personal:', 'source': '...",Human: <|im_start|>system\nAnda adalah asisten...,"[{'Header 2': '2.3.1 Antropometri', 'source': ...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,Human: <|im_start|>system\n Anda adal...,"[{'Header 2': '1.1 Tujuan Pelaksanaan', 'sourc...",[\n INFO KLINIS PASIEN:\n - Diagnosi...,"[6138, 6164, 6149]","[6126, 6146, 6148]","[6121, 4922, 6120]",Peningkatan berat badan pasien akan memberikan...,Peningkatan berat badan pasien dengan jenis ke...

In [6]:
def calc_retrieval_metrics(row, retrieved_col, k=3):
    retrieved_ids = row[retrieved_col][:k] # Potong hasil sesuai K
    ground_truth_ids = row['ground_truth_ids']
    
    gt_set = set(ground_truth_ids)
    
    # Deteksi mana yang "Hit" (Benar) di urutan top K
    hits = [1 if doc_id in gt_set else 0 for doc_id in retrieved_ids]
    
    # 1. Recall@K = (Jumlah Benar) / (Total Kunci Jawaban)
    recall = sum(hits) / len(gt_set) if len(gt_set) > 0 else 0.0
    
    # 2. Precision@K = (Jumlah Benar) / K
    precision = sum(hits) / k if k > 0 else 0.0
    
    # 3. MRR@K = 1 / (Ranking pertama yang benar)
    mrr = 0.0
    for i, hit in enumerate(hits):
        if hit == 1:
            mrr = 1.0 / (i + 1)
            break
            
    return pd.Series([precision, recall, mrr])

# Menetapkan Nilai K (Silakan ubah ke 3 atau 10 sesuai kebutuhan)
print(f"2. Menghitung Metrik Retrieval untuk K={K_VALUE}...")

# Hitung untuk Baseline
df[['baseline_Precision@K', 'baseline_Recall@K', 'baseline_MRR@K']] = df.apply(
    lambda row: calc_retrieval_metrics(row, 'baseline_retrieved_ids', k=K_VALUE), axis=1
)

# Hitung untuk Fusion
df[['fusion_Precision@K', 'fusion_Recall@K', 'fusion_MRR@K']] = df.apply(
    lambda row: calc_retrieval_metrics(row, 'fusion_retrieved_ids', k=K_VALUE), axis=1
)

2. Menghitung Metrik Retrieval untuk K=3...

In [7]:
print("\n3. Mempersiapkan data untuk evaluasi Ragas (LLM-as-a-Judge)...")

# Format Dataset untuk Ragas Baseline
dataset_baseline = Dataset.from_dict({
    "question": df["question"].tolist(),
    "answer": df["clean_baseline_answer"].tolist(), # MENGGUNAKAN JAWABAN BERSIH
    "contexts": df["baseline_retrieved_contexts"].tolist(),
    "ground_truth": df["ground_truth"].tolist()
})

# Format Dataset untuk Ragas Fusion
dataset_fusion = Dataset.from_dict({
    "question": df["question"].tolist(),
    "answer": df["clean_fusion_answer"].tolist(), # MENGGUNAKAN JAWABAN BERSIH
    "contexts": df["fusion_retrieved_contexts"].tolist(),
    "ground_truth": df["ground_truth"].tolist()
})

print("\n> Menjalankan Evaluasi Ragas untuk BASELINE...")
ragas_result_baseline = evaluate(
    dataset_baseline,
    metrics=[faithfulness, answer_relevancy],
    llm=evaluator_llm,
    embeddings=evaluator_embeddings
)

print("\n> Menjalankan Evaluasi Ragas untuk FUSION...")
ragas_result_fusion = evaluate(
    dataset_fusion,
    metrics=[faithfulness, answer_relevancy],
    llm=evaluator_llm,
    embeddings=evaluator_embeddings
)

3. Mempersiapkan data untuk evaluasi Ragas (LLM-as-a-Judge)...

> Menjalankan Evaluasi Ragas untuk BASELINE...

Evaluating:  19%|█▉        | 19/100 [01:21<02:54,  2.15s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  20%|██        | 20/100 [01:26<03:22,  2.53s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  22%|██▏       | 22/100 [01:29<02:59,  2.31s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  23%|██▎       | 23/100 [01:37<04:09,  3.24s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  27%|██▋       | 27/100 [01:50<03:58,  3.27s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  33%|███▎      | 33/100 [02:12<04:16,  3.82s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  35%|███▌      | 35/100 [02:20<04:12,  3.88s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  39%|███▉      | 39/100 [02:33<03:29,  3.43s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  42%|████▏     | 42/100 [02:45<03:48,  3.95s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  52%|█████▏    | 52/100 [03:00<01:39,  2.07s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  53%|█████▎    | 53/100 [03:04<01:54,  2.43s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  61%|██████    | 61/100 [03:34<01:50,  2.83s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  66%|██████▌   | 66/100 [03:45<01:16,  2.26s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  72%|███████▏  | 72/100 [04:11<01:43,  3.69s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  78%|███████▊  | 78/100 [04:20<00:49,  2.25s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  79%|███████▉  | 79/100 [04:28<01:07,  3.21s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  92%|█████████▏| 92/100 [05:01<00:19,  2.47s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating: 100%|██████████| 100/100 [05:42<00:00,  3.42s/it]

> Menjalankan Evaluasi Ragas untuk FUSION...

Evaluating:   3%|▎         | 3/100 [00:33<21:55, 13.56s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   9%|▉         | 9/100 [00:45<06:35,  4.34s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  19%|█▉        | 19/100 [01:10<03:11,  2.36s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  22%|██▏       | 22/100 [01:21<03:39,  2.81s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  26%|██▌       | 26/100 [01:28<02:50,  2.31s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  41%|████      | 41/100 [02:27<03:25,  3.48s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  54%|█████▍    | 54/100 [03:01<02:14,  2.92s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  64%|██████▍   | 64/100 [03:23<01:12,  2.02s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  65%|██████▌   | 65/100 [03:31<01:39,  2.84s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  67%|██████▋   | 67/100 [03:41<01:56,  3.53s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  70%|███████   | 70/100 [03:46<01:23,  2.79s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  74%|███████▍  | 74/100 [04:10<01:49,  4.21s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  81%|████████  | 81/100 [04:21<00:44,  2.36s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  84%|████████▍ | 84/100 [04:33<00:44,  2.75s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating: 100%|██████████| 100/100 [05:34<00:00,  3.34s/it]

In [8]:
print("\n" + "="*50)
print(f"HASIL EVALUASI AKHIR (Top-K = {K_VALUE})")
print("="*50)

df_ragas_baseline = ragas_result_baseline.to_pandas()
df_ragas_fusion = ragas_result_fusion.to_pandas()

# 2. Hitung rata-rata (mean) dari kolom metrik, otomatis mengabaikan nilai NaN
baseline_faithfulness_mean = df_ragas_baseline['faithfulness'].mean()
baseline_answer_rel_mean = df_ragas_baseline['answer_relevancy'].mean()

fusion_faithfulness_mean = df_ragas_fusion['faithfulness'].mean()
fusion_answer_rel_mean = df_ragas_fusion['answer_relevancy'].mean()

summary_df = pd.DataFrame({
    "Metrik": [
        f"Context Recall@{K_VALUE}", 
        f"Context Precision@{K_VALUE}", 
        f"MRR@{K_VALUE}", 
        "Faithfulness (Ragas)", 
        "Answer Relevancy (Ragas)"
    ],
    "RAG Baseline": [
        df['baseline_Recall@K'].mean(),
        df['baseline_Precision@K'].mean(),
        df['baseline_MRR@K'].mean(),
        baseline_faithfulness_mean,
        baseline_answer_rel_mean
    ],
    "RAG Fusion": [
        df['fusion_Recall@K'].mean(),
        df['fusion_Precision@K'].mean(),
        df['fusion_MRR@K'].mean(),
        fusion_faithfulness_mean,
        fusion_answer_rel_mean
    ]
})

import IPython.display as display
display.display(summary_df)

==================================================
HASIL EVALUASI AKHIR (Top-K = 3)
==================================================

                     Metrik  RAG Baseline  RAG Fusion
0          Context Recall@3      0.133333    0.080000
1       Context Precision@3      0.133333    0.080000
2                     MRR@3      0.266667    0.190000
3      Faithfulness (Ragas)      0.544991    0.673186
4  Answer Relevancy (Ragas)      0.378343    0.404372

In [9]:
summary_df.to_csv(f'evaluation_@{K_VALUE}.csv')